# Generated by Django 2.1.7 on 2019-04-06 21:18

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InvitationToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='When was the token generated')),
                ('ip_address',
                 models.GenericIPAddressField(default='127.0.0.1', verbose_name='The IP address of this session')),
                ('user_agent', models.CharField(default='', max_length=256, verbose_name='HTTP User Agent')),
                (
                'user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitation_tokens',
                                          to=settings.AUTH_USER_MODEL,
                                          verbose_name='The User which is associated to this invitation token')),
            ],
        ),
    ]
