# Generated by Django 2.1.7 on 2019-04-06 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drf_simple_invite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitationtoken',
            name='ip_address',
            field=models.GenericIPAddressField(default='127.0.0.1', verbose_name='The IP address of this session'),
        ),
        migrations.AddField(
            model_name='invitationtoken',
            name='user_agent',
            field=models.CharField(default='', max_length=256, verbose_name='HTTP User Agent'),
        ),
    ]
